
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJFrIPGqNrTes6j4xAg5hOJdANrSQYcao',
    appId: '1:279852881436:web:09f40c4424084409f9f1d9',
    messagingSenderId: '279852881436',
    projectId: 'apptransfert-b2811',
    authDomain: 'apptransfert-b2811.firebaseapp.com',
    storageBucket: 'apptransfert-b2811.appspot.com',
    measurementId: 'G-03J8CM27LQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP2MZSGexpOYKR6SH7Ia5I_vfDvJPZ15s',
    appId: '1:279852881436:android:3c7e9c3352fd5e5ef9f1d9',
    messagingSenderId: '279852881436',
    projectId: 'apptransfert-b2811',
    storageBucket: 'apptransfert-b2811.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVwG2pthwvQQHfItf3slqFNZG016OruRg',
    appId: '1:279852881436:ios:9ab6db1ec2f44e5af9f1d9',
    messagingSenderId: '279852881436',
    projectId: 'apptransfert-b2811',
    storageBucket: 'apptransfert-b2811.appspot.com',
    iosBundleId: 'com.example.appTransaction',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVwG2pthwvQQHfItf3slqFNZG016OruRg',
    appId: '1:279852881436:ios:e67136861e5befd3f9f1d9',
    messagingSenderId: '279852881436',
    projectId: 'apptransfert-b2811',
    storageBucket: 'apptransfert-b2811.appspot.com',
    iosBundleId: 'com.example.appTransaction.RunnerTests',
  );
}
